[package]
name = "thalassic"
version = "0.1.0"
edition = "2021"

[dependencies]
gputter = { path = "../gputter" }
bytemuck.workspace = true
nalgebra.workspace = true
fxhash.workspace = true
parking_lot.workspace = true
